apiVersion: v1
kind: Pod

metadata:
  name: app-with-config

spec:
  containers:
    - name: myapp
      image: busybox

      command:
        - "sh"
        - "-c"
        - "cat /config/app.properties && sleep 3600"

      volumeMounts:
        - name: config-volume
          mountPath: /config

  volumes:
    - name: config-volume
      configMap:
        name: app-config