apiVersion: v1
kind: Pod
metadata:
  name: html-pod

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html

  volumes:
    - name: html-volume
      configMap:
        name: html-config