apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-prevents-privilege
spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true

      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

        volumeMounts:
          - name: tmp
            mountPath: /tmp

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
        - name: tmp
          emptyDir: {}
