apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats-rs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: cats

  template:
    metadata:
      labels:
        app: cats

    spec:
      containers:
        - name: cats-container
          image: hashicorp/http-echo
          args:
            - "-text=Cats App"

          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: cats-service

spec:
  type: ClusterIP

  selector:
    app: cats

  ports:
    - port: 80
      targetPort: 5678

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dogs-rs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: dogs

  template:
    metadata:
      labels:
        app: dogs

    spec:
      containers:
        - name: dogs-container
          image: hashicorp/http-echo
          args:
            - "-text=Dogs App"

          ports:
            - containerPort: 5678

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dogs-rs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: dogs

  template:
    metadata:
      labels:
        app: dogs

    spec:
      containers:
        - name: dogs-container
          image: hashicorp/http-echo
          args:
            - "-text=dogs App"

          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: dogs-service

spec:
  type: ClusterIP
  selector:
    app: dogs

  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: birds-service

spec:
  type: ClusterIP

  selector:
    app: birds

  ports:
    - port: 80
      targetPort: 5678

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: birds-rs

spec:
  replicas: 3

  selector:
    matchLabels:
      app: birds

  template:
    metadata:
      labels:
        app: birds

    spec:
      containers:
        - name: birds-container
          image: hashicorp/http-echo
          args:
            - "-text=birds App"

          ports:
            - containerPort: 5678
