name: CI

on:
  push: 
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Debug folder structure
      run: ls -la
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      working-directory: ./back #path to the working directory
      run: mvn clean package -DskipTests=false
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }} #jwt token that we added
    # ── 2. Build the frontend ────────────────────────
  frontend:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory:  ./front
        run:  npm ci

      - name:  Run npm Build
        working-directory:  ./front
        run:  npm run build
